
export const SAVE_USER_SETTING_NIGHTMODE = 'SAVE_USER_SETTING_NIGHTMODE';
export const SAVE_USER_SETTING_AUTORELOAD = 'SAVE_USER_SETTING_AUTORELOAD';
export const SAVE_USER_SETTING_FULLSCREENLOCK = 'SAVE_USER_SETTING_FULLSCREENLOCK';
export const SAVE_USER_SETTING_SCREENLOCK = 'SAVE_USER_SETTING_SCREENLOCK';
export const SAVE_USER_SETTING_HEADERCLOCK = 'SAVE_USER_SETTING_HEADERCLOCK';
export const SAVE_USER_SETTING_AUTONIGHTMODE = 'SAVE_USER_SETTING_AUTONIGHTMODE';
export const SAVE_USER_SETTING_AUTONIGHTMODE_RANGE = 'SAVE_USER_SETTING_AUTONIGHTMODE_RANGE';
export const SAVE_USER_SETTING_AUTONIGHTMODE_INVERT = 'SAVE_USER_SETTING_AUTONIGHTMODE_INVERT';