// State mutations

export const LOAD_CONFIG = 'LOAD_CONFIG';
export const LOAD_QUANTITY_UNITS = 'LOAD_QUANTITY_UNITS';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const UPDATE_USER_SETTING_NIGHTMODE = 'UPDATE_USER_SETTING_NIGHTMODE';
export const UPDATE_USER_SETTING_AUTORELOAD = 'UPDATE_USER_SETTING_AUTORELOAD';
export const UPDATE_USER_SETTING_FULLSCREENLOCK = 'UPDATE_USER_SETTING_FULLSCREENLOCK';
export const UPDATE_USER_SETTING_SCREENLOCK = 'UPDATE_USER_SETTING_SCREENLOCK';
export const UPDATE_USER_SETTING_HEADERCLOCK = 'UPDATE_USER_SETTING_HEADERCLOCK';
export const UPDATE_USER_SETTING_AUTONIGHTMODE = 'UPDATE_USER_SETTING_AUTONIGHTMODE';
export const UPDATE_USER_SETTING_AUTONIGHTMODE_RANGE = 'UPDATE_USER_SETTING_AUTONIGHTMODE_RANGE';
export const UPDATE_USER_SETTING_AUTONIGHTMODE_INVERT = 'UPDATE_USER_SETTING_AUTONIGHTMODE_INVERT';
export const UPDATE_USER_SETTING_UNSAVED_AUTONIGHTMODE_RANGE = 'UPDATE_USER_SETTING_UNSAVED_AUTONIGHTMODE_RANGE';
export const UPDATE_USER_SETTING_PREFERRED_BARCODE_CAMERA = 'UPDATE_USER_SETTING_PREFERRED_BARCODE_CAMERA';
export const DELETE_USER_SETTING_PREFERRED_BARCODE_CAMERA = 'DELETE_USER_SETTING_PREFERRED_BARCODE_CAMERA';