blank_issues_enabled: false
contact_links:
    - name: Question / Help
      url: https://github.com/mistressofjellyfish/not-grocy/discussions
      about: Head over to Discussions for general Questions and help.
