name: Check PHP formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@e02a1810e66ae357773a8f82626c7965d13ca75c # pinned 2.11.0
      with:
        php-version: ${{ matrix.php-version }}
    - run: mkdir --parents tools/php-cs-fixer
    - run: composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
    - run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix php --verbose --dry-run
